### ISSUE TITLE
AI: Claude Code Login file path not being found on Mac

### ISSUE THREAD

**Issue by desaisoam** [zed-industries/zed#38526]
### Description

Steps to trigger the problem:
1. New installation of Zed on Mac silicon processor
2. Open claude code agent 
3. Type "/login"

**Expected Behavior**:
Take you to anthropic login page 
**Actual Behavior**:
Errors and says file not found. The file path is being cutoff, I believe it should go to /Users/user/Library/Application Support/Zed/external_agents/claude-code-acp/0.4.3/node_modules/@zed-industries/claude-code-acp/dist/index.js

error:

node:internal/modules/cjs/loader:1408
  throw err;
  ^

Error: Cannot find module '/Users/user/Library/Application'
    at Function._resolveFilename (node:internal/modules/cjs/loader:1405:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1061:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1066:22)
    at Function._load (node:internal/modules/cjs/loader:1215:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:151:5)
    at node:internal/main/run_main_module:33:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

### Model Provider Details
- Provider: Anthropic
- Model Name: default 
- Mode: Agent Panel 
- Other Details (MCPs, other settings, etc):

### Zed Version and System Specs

Zed: v0.204.3 (Zed) 
OS: macOS 15.1.1
Memory: 16 GiB
Architecture: aarch64

**Comment by ConradIrwin** [comment]
Thanks for the heads up, I can reproduce this and am looking into why.

**Comment by ConradIrwin** [comment]
Ok, this is a gnarly one.

The original problem was possibly? fixed by e9b4f59e0f2b732424d830b3c49119fd3c233b59 That said, it seems like cherry-picking this to stable does not fix it.

But the fix regressed with 59a609c9fcebd3f641e64a498e15e3cf2042a648 (which was cherry-picked to preview as ab4687391a00d51a184d1c6b08e093591228405b).

So I think the reason it's broken on stable is different from the reason it's broken on main/preview; I'm still trying to narrow down why it broke on stable to get a targeted fix out.

**Comment by benbrandt** [comment]
@desaisoam this should be fixed in the latest version of Zed! Let us know if you are still running into issues.
