### PR TITLE
Fix bytes 1.5.0 failed to build on Rust 1.78

### PR DESCRIPTION
**Pull request by Xuanwo**
### Problems

bytes 1.5 failed to build on linux with rust 1.78:

```shell
error[E0423]: cannot initialize a tuple struct which contains private fields
    --> /home/xuanwo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bytes-1.5.0/src/bytes.rs:1148:18
     |
1148 |     let shared = Box(shared);
     |                  ^^^
     |
note: constructor is not visible here due to private fields
    --> /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/alloc/src/boxed.rs:200:14
     |
     = note: private field
     |
     = note: private field
help: you might have meant to use an associated function to build this type
     |
1148 |     let shared = Box::new(_);
     |                     ~~~~~~~~
1148 |     let shared = Box::new_uninit();
     |                     ~~~~~~~~~~~~~~
1148 |     let shared = Box::new_zeroed();
     |                     ~~~~~~~~~~~~~~
1148 |     let shared = Box::new_in(_, _);
     |                     ~~~~~~~~~~~~~~
       and 10 other candidates
help: consider using the `Default` trait
     |
1148 |     let shared = <Box as std::default::Default>::default();
     |                  +    ~~~~~~~
```

Release Notes:

- N/A

### CODE REVIEW

**Comment by Xuanwo** [comment]
@cla-bot check

**Review by maxdeviant — CHANGES_REQUESTED** [review]
It looks like this is just a `Cargo.lock` change? I don't think we should be just be modifying the `Cargo.lock` by hand.

Also, if this is a problem why isn't the Linux CI failing?

**Comment by Xuanwo** [comment]
Thanks for pointing out. For reasons I don't know, the `bytes 1.5.0` at my local is:

```rust
let shared = Box(shared);
```

This PR is not needed.
