### ISSUE TITLE
livekit-libwebrtc fails to compile on NixOS against PipeWire 1.5+ (missing spa/pod/iter.h include)

### ISSUE THREAD

**Issue by coryzibell** [zed-industries/zed#54225]
## Summary

Zed's bundled `livekit-libwebrtc-137-unstable-2025-11-24` (defined in [`nix/livekit-libwebrtc/package.nix`](https://github.com/zed-industries/zed/blob/main/nix/livekit-libwebrtc/package.nix)) pins a webrtc revision that predates the `spa/pod/iter.h` include fix for PipeWire 1.5+. Building against any nixpkgs (including Zed's own pinned `nixos-unstable`) that carries PipeWire 1.5.81 or later fails.

Fortunately, upstream nixpkgs already carries the fix as a small 3-line patch — [`pkgs/by-name/li/livekit-libwebrtc/pipewire-1.5.patch`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/by-name/li/livekit-libwebrtc/pipewire-1.5.patch), introduced in [`6a6b02f3c1bf9a7e135a26698e507f0cae1f805f`](https://github.com/NixOS/nixpkgs/commit/6a6b02f3c1bf9a7e135a26698e507f0cae1f805f) by [@Thaodan](https://github.com/Thaodan). Carrying it in Zed's own `patches` list would clear the failure without invalidating `zed.cachix.org` substitutes.

## Repro

NixOS unstable (PipeWire >= 1.5.81), `nix build .#default`:

```
[2989/3467] CXX obj/modules/video_capture/video_capture_internal_impl/pipewire_session.o
FAILED: [code=1] obj/modules/video_capture/video_capture_internal_impl/pipewire_session.o
../../modules/video_capture/linux/pipewire_session.cc:148:10: error: 'spa_pod_object_find_prop' was not declared in this scope; did you mean 'spa_pod_parser_object_find_prop'?
../../modules/video_capture/linux/pipewire_session.cc:150:11: error: 'spa_pod_get_values' was not declared in this scope
../../modules/video_capture/linux/pipewire_session.cc:173:9: error: 'spa_pod_get_values' was not declared in this scope
../../modules/video_capture/linux/pipewire_session.cc:216:12: error: 'spa_pod_object_find_prop' was not declared in this scope; did you mean 'spa_pod_parser_object_find_prop'?
../../modules/video_capture/linux/pipewire_session.cc:220:11: error: 'spa_pod_get_values' was not declared in this scope
```

(Zed's own flake pins `nixpkgs = nixos-unstable`, which carries PipeWire 1.6.2, so this reproduces on a plain `nix build github:zed-industries/zed` against anything outside the cachix/garnix prebuilt window.)

## Root cause

In PipeWire 1.5+, `spa_pod_object_find_prop` and `spa_pod_get_values` moved/are declared in `spa/pod/iter.h`, and the two affected TUs no longer get them transitively through `spa/pod/parser.h`. The fix is adding the missing include to:

- `modules/video_capture/linux/pipewire_session.cc`
- `modules/desktop_capture/linux/wayland/shared_screencast_stream.cc`

## Proposed fix

Extend the `patches` list in `nix/livekit-libwebrtc/package.nix` with nixpkgs's `pipewire-1.5.patch`. A drop-in way:

```nix
patches = [
  # ...existing patches...
  (fetchpatch {
    name = "pipewire-1.5.patch";
    url = "https://raw.githubusercontent.com/NixOS/nixpkgs/6a6b02f3c1bf9a7e135a26698e507f0cae1f805f/pkgs/by-name/li/livekit-libwebrtc/pipewire-1.5.patch";
    hash = "sha256-ei3A7ArBMt2b0bF6bzjIG0SwAtoi2dabyfBE8btUThM=";
  })
];
```

Happy to send a PR with this exact change if it's useful.

## Workaround for downstream consumers

Overlay-level override that rebuilds `LK_CUSTOM_WEBRTC` with the patch applied, verified on x86_64-linux / PipeWire 1.6.2:

```nix
(final: prev: {
  zed-editor = let
    zedPkg = inputs.zed-editor.packages.${prev.stdenv.hostPlatform.system}.default;
    patchedWebrtc = zedPkg.LK_CUSTOM_WEBRTC.overrideAttrs (old: {
      patches = (old.patches or []) ++ [
        (prev.fetchpatch {
          name = "pipewire-1.5.patch";
          url = "https://raw.githubusercontent.com/NixOS/nixpkgs/6a6b02f3c1bf9a7e135a26698e507f0cae1f805f/pkgs/by-name/li/livekit-libwebrtc/pipewire-1.5.patch";
          hash = "sha256-ei3A7ArBMt2b0bF6bzjIG0SwAtoi2dabyfBE8btUThM=";
        })
      ];
    });
  in zedPkg.overrideAttrs (old: {
    env = (old.env or {}) // { LK_CUSTOM_WEBRTC = "${patchedWebrtc}"; };
  });
})
```

The `env.LK_CUSTOM_WEBRTC` override flows through cleanly; `cargoVendorDir` doesn't reference it, so the crane vendor cache stays valid.

## Environment

- NixOS unstable
- PipeWire 1.6.2
- glibc 2.42
- gcc, not clang (linux build uses `is_clang=false`)

**Comment by stefanboca** [comment]
Instead of patching the vendored library, I found that `livekit-libwebrtc` from the latest `nixos-unstable` also works. I did also have to override the env var in `cargoArtifacts`:
```nix
final: prev: {
  zed-editor = (inputs.zed-editor.overlays.default final prev).zed-editor.overrideAttrs (oldAttrs: {
    env = (oldAttrs.env or {}) // {LK_CUSTOM_WEBRTC = final.livekit-libwebrtc;};
    cargoArtifacts = oldAttrs.cargoArtifacts.overrideAttrs (oldAttrs': {
      env = (oldAttrs'.env or {}) // {LK_CUSTOM_WEBRTC = final.livekit-libwebrtc;};
    });
  });
}
```
