### PR TITLE
Add Arduino language support for .ino files

### PR DESCRIPTION
**Pull request by P0SlX**
Fixes clangd AST compilation errors and "fe_expected_compiler_job" warnings when opening .ino files introduced by #35467.

Creates dedicated Arduino language using C++ grammar but separate from main C++ language to avoid LSP conflicts while maintaining syntax highlighting and code navigation.

Release Notes:

- Added syntax highlighting for .ino files

### CODE REVIEW

**Comment by P0SlX** [comment]
@cla-bot check

**Comment by maxdeviant** [comment]
It seems like this should get moved to an Arduino extension, if we’re creating a new language for it.

**Comment by SomeoneToIgnore** [comment]
I agree with @\maxdeviant here: Zed Core (this repo) strives to have as less languages inside this repo as possible, see https://github.com/zed-industries/zed/discussions/35867 for some discussions on that topic and https://github.com/zed-industries/zed/pull/36323 as a very recent related change, that moves away another language into extensions.

So, all these nice grammar files should be going to https://github.com/zed-industries/extensions instead, as "Arduino language" is not something we're ready to accept into the "core" languages.
