### PR TITLE
agent_ui: Fix missing arguments in external_thread calls for conflict resolution

### PR DESCRIPTION
**Pull request by ghost**
Fixes compilation error introduced in #49807 where external_thread calls for conflict resolution actions were missing 3 required arguments (cwd, title, focus).

Reported issue: https://github.com/zed-industries/zed/issues/51199

Release Notes:
- N/A

### CODE REVIEW

**Comment by danilo-leal** [comment]
Heya, thanks for the PR & issue! I'm closing this one though as I just opened one for the same thing here: https://github.com/zed-industries/zed/pull/51200.
