### ISSUE TITLE
Windows compilation error after wasmtime v21 bump

### ISSUE THREAD

**Issue by sndels** [zed-industries/zed#15368]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I'm getting a compilation error on the patched tree-sitter introduced in d755d29577dcc409ca7e067d0d8e03af57b09ced
```
error: failed to run custom build command for `tree-sitter v0.22.6 (https://github.com/tree-sitter/tree-sitter?rev=7f4a57817d58a2f134fe863674acad6bbf007228#7f4a5781)
...
....cargo\registry\src\index.crates.io-6f17d22bba15001f\wasmtime-c-api-impl-21.0.1\include\wasmtime/val.h(10): fatal error C1083: Cannot open include file: 'stdalign.h': No such file or directory
````

### Environment

Zed: d755d29 and fee49fc sources
OS: Windows 10.0.19045
Memory: 31.9 GiB
Architecture: x86_64

1.80-x86_64-pc-windows-msvc
MSVC 19.40.33813.0 (VS2022)
Windows SDK 10.0.19041.0

**Comment by SomeoneToIgnore** [comment]
Have you tried searching what is `stdalign.h` and why is it missing on Windows?

https://github.com/google-deepmind/mujoco/issues/862#issuecomment-1876104240 claims you have to update the SDK and that this file is a "standard" thing in other OSes.

https://developer.microsoft.com/en-us/windows/downloads/sdk-archive/ claims that there's at least `Windows 10 SDK version 2104 (10.0.20348.0)` to upgrade to.

**Comment by sndels** [comment]
Ah, I did try some searches but somehow missed those 🤦 Bumping the SDK indeed sorted this out, sorry for the bother 🙏

**Comment by sndels** [comment]
Closing
